// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PARTS_ORDER.Database;

#nullable disable

namespace PARTS_ORDER.Migrations
{
    [DbContext(typeof(DatabaseInitializer))]
    [Migration("20230622183814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PARTS_ORDER.Database.APP_AUTH_Tables.LOGIN_USERS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ADMIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HASŁO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOGIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LOGIN_USERS", (string)null);
                });

            modelBuilder.Entity("PARTS_ORDER.Database.PARTS_ORDER_Tables.OPERATOR", b =>
                {
                    b.Property<int>("PESEL")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PESEL"));

                    b.Property<string>("IMIĘ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAZWISKO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STANOWISKO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PESEL");

                    b.ToTable("OPERATOR", (string)null);
                });

            modelBuilder.Entity("PARTS_ORDER.Database.Tables.CHECK_PARTS", b =>
                {
                    b.Property<int>("ID_CZĘŚCI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CZĘŚCI"));

                    b.Property<int>("ILOŚĆ")
                        .HasColumnType("int");

                    b.Property<int>("KLUCZ_PRODUKTU")
                        .HasColumnType("int");

                    b.Property<string>("NAZWA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WYDAWCA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_CZĘŚCI");

                    b.ToTable("CHECK_PARTS", (string)null);
                });

            modelBuilder.Entity("PARTS_ORDER.Database.Tables.PARTS_SELLER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DOSTĘPNOŚĆ")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("ID_CZĘŚCI")
                        .HasColumnType("int");

                    b.Property<double>("KOSZT")
                        .HasColumnType("float");

                    b.Property<string>("WYDAWCA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PARTS_SELLER", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
